<a href="https://colab.research.google.com/github/GustavoDavila77/Curso-de-introducci-n-al-machine-learning/blob/master/clase_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import numpy as np

import pandas as pd

# Trabajando con tensores

---



In [0]:
torch.__version__

'1.3.1'

In [0]:
# tensor de unos - dimensión 2x2
tensor_a = torch.ones(2,2)
tensor_a 

tensor([[1., 1.],
        [1., 1.]])

In [0]:
#tensor 2x2 de valores aleatorios
tensor_b = torch.Tensor(2,2)
print(tensor_b)

#como se va a modificar el tensor se pone _ al final de uniform
#tensor con valores entre 0 y 1
tensor_b.uniform_(0,1)

tensor([[1.2166e-35, 0.0000e+00],
        [3.7835e-44, 0.0000e+00]])


tensor([[0.8021, 0.6380],
        [0.8233, 0.5739]])

In [0]:
#otra forma de generar valores aleatorios
# rand por defecto los genera entre 0 y 1
tensor_c = torch.rand(2,2)
tensor_c 

tensor([[0.1773, 0.1577],
        [0.0627, 0.4772]])

In [0]:
sumatensores = tensor_a + tensor_b
sumatensores

tensor([[1.8021, 1.6380],
        [1.8233, 1.5739]])

In [0]:
#para saber las dimensiones
sumatensores.shape
#cambio de dimens a 1 fila 4 cols
redimensionsuma = sumatensores.view(1,4)
redimensionsuma

tensor([[1.8021, 1.6380, 1.8233, 1.5739]])

In [0]:
#Tensor con t en mayus genera un tensor de nums random
#tensor en t minus me permite crear un tensor
points = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
print(points)
#modificar el elemento 2 por 5.5
points[0][1] = 5.5
print(points)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1.0000, 5.5000],
        [3.0000, 4.0000]])


In [0]:
#para observar como se esta almacenando
points.storage()

 1.0
 5.5
 3.0
 4.0
[torch.FloatStorage of size 4]

In [0]:
#como paso de un numero al siguiente dependiendo
# de las dimensiones
#es el salto necesario para ir de un elemento a otro en la
#dimensión especificada
points, points.stride()
#resultado (2,1) de 1.0 a 3.0 hay que dar dos pasos
#y de 5.5 a 3.0 hay un solo paso 


(tensor([[1.0000, 5.5000],
         [3.0000, 4.0000]]), (2, 1))

In [0]:
#transpuesta del tensor
#en otras palabras es poner las columnas como filas
p_t = points.t()
p_t, p_t.storage(), p_t.stride()

(tensor([[1.0000, 3.0000],
         [5.5000, 4.0000]]),  1.0
  5.5
  3.0
  4.0
 [torch.FloatStorage of size 4], (1, 2))

In [0]:
tensor_x = torch.tensor([1,2,3,4])
#se agrego una dimensión en filas
#tensor_x, torch.unsqueeze(tensor_x, 0)
#se agrego una dimensión en col
tensor_x , torch.unsqueeze(tensor_x,1)


(tensor([1, 2, 3, 4]), tensor([[1],
         [2],
         [3],
         [4]]))

In [0]:
#pasar de numeros random en numpy a un tensor
numpyArray = np.random.randn(2,2)

from_numpy = torch.from_numpy(numpyArray)
from_numpy


tensor([[0.5097, 0.3037],
        [2.9358, 0.7387]], dtype=torch.float64)

# Representar datos con tensores

---





In [0]:
print(from_numpy)
#mean for all nums
print(torch.mean(from_numpy))
#mean for cols
print(torch.mean(from_numpy, dim= 0))
#mean for rows
print(torch.mean(from_numpy, dim= 1))

tensor([[0.5097, 0.3037],
        [2.9358, 0.7387]], dtype=torch.float64)
tensor(1.1220, dtype=torch.float64)
tensor([1.7227, 0.5212], dtype=torch.float64)
tensor([0.4067, 1.8372], dtype=torch.float64)


In [0]:
#calculo de la desviación standar
torch.std(from_numpy, dim= 1)

tensor([0.1456, 1.5536], dtype=torch.float64)

In [0]:
#guardar en el disco
torch.save(from_numpy, 'tensor.t')

In [0]:
#cargar datos de memoria
load = torch.load('tensor.t')
load

tensor([[0.5097, 0.3037],
        [2.9358, 0.7387]], dtype=torch.float64)

In [0]:
url = "https://raw.githubusercontent.com/amanthedorkknight/fifa18-all-player-statistics/master/2019/data.csv"
dataframe = pd.read_csv(url)
dataframe

Unnamed: 0      ID  ... GKReflexes  Release Clause
0               0  158023  ...        8.0         €226.5M
1               1   20801  ...       11.0         €127.1M
2               2  190871  ...       11.0         €228.1M
3               3  193080  ...       94.0         €138.6M
4               4  192985  ...       13.0         €196.4M
...           ...     ...  ...        ...             ...
18202       18202  238813  ...        9.0           €143K
18203       18203  243165  ...       12.0           €113K
18204       18204  241638  ...       13.0           €165K
18205       18205  246268  ...        9.0           €143K
18206       18206  246269  ...        9.0           €165K

[18207 rows x 89 columns]

In [0]:
dataframe.columns

Index(['Unnamed: 0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag',
       'Overall', 'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingT

In [0]:
#for this case professor select any column with objective of 
#explain overall's players (rendimiento)
subset = dataframe[['Overall', 'Age', 'International Reputation', 'Weak Foot', 'Skill Moves']].dropna(axis=0, how= 'any')

#example columns after 'overall' 
columns = subset.columns[1:]

#convert values to float
players = torch.tensor(subset.values).float()
#shape output rows and colums 
players.shape, players.type()

(torch.Size([18159, 5]), 'torch.FloatTensor')

In [0]:
#get players information without overall
# all rows and all cols minus first[:,1:]
data = players[:, 1:]
data , data.shape

(tensor([[31.,  5.,  4.,  4.],
         [33.,  5.,  4.,  5.],
         [26.,  5.,  5.,  5.],
         ...,
         [16.,  1.,  3.,  2.],
         [17.,  1.,  3.,  2.],
         [16.,  1.,  3.,  2.]]), torch.Size([18159, 4]))

In [0]:
#get objective, only first column
target = players[:, 0]
target, target.shape

(tensor([94., 94., 92.,  ..., 47., 47., 46.]), torch.Size([18159]))

In [0]:
# mean of data
mean = torch.mean(data, dim= 0)
mean

tensor([25.1225,  1.1132,  2.9473,  2.3613])

In [0]:
# standard deviation of data
std = torch.std(data, dim= 0)
std

tensor([4.6706, 0.3940, 0.6605, 0.7562])

In [0]:
# normalización(standardization) de los datos
# equation found in internet is 
#norm = (data- mean) / std
norm = (data - mean) / torch.sqrt(std)
norm


tensor([[ 2.7196,  6.1919,  1.2953,  1.8845],
        [ 3.6450,  6.1919,  1.2953,  3.0345],
        [ 0.4060,  6.1919,  2.5258,  3.0345],
        ...,
        [-4.2211, -0.1804,  0.0648, -0.4155],
        [-3.7584, -0.1804,  0.0648, -0.4155],
        [-4.2211, -0.1804,  0.0648, -0.4155]])

In [0]:
#good, average and notsogood players
#ge (great or equal) -- great than -- less than -- less or equal
good = data[torch.ge(target, 85)]
average = data[torch.gt(target, 70) & torch.lt(target, 85)]
notSoGood = data[torch.le(target, 70)]

goodMean = torch.mean(good, dim= 0)
averageMean = torch.mean(average, dim = 0)
notSoGoodMean = torch.mean(notSoGood, dim = 0)

#goodMean, averageMean, notSoGood

# print more beutiful 
#zip agrupa multiples variables
#{:25} el número max de caracteres del name de las col
#{:6.2f} para imprimir con 2 cifras decimales
for i, args in enumerate(zip(columns, goodMean, averageMean, notSoGoodMean)):
  print('{:25} {:6.2f} {:6.2f} {:6.2f}'.format(*args))

Age                        28.35  27.23  24.37
International Reputation    3.38   1.36   1.01
Weak Foot                   3.45   3.11   2.89
Skill Moves                 3.04   2.75   2.22
